world: world
nether-world: world_nether

teams-max-slots: 50

spawn-location:
  x: 0
  y: 100
  z: 0

active-time: 120
time-format: "%h%ч. %m%м. %s%с."

chat-global-format: "§x§f§b§e§6§2§4ɢ §7| %team%§f %player%§7: %text%"
inventory-return-price: 350
messages:
  teleport-ok: "Телепортирую..."
  no-permission: "§cНедостаточно прав"
  no-team: "Команда не найдена"
  you-team-member: "Вы уже состоите в команде"
  team-full: "Команда переполнена"
  player-no-member: "Игрок не является участником команды"
  no-balance: "У Вас недостаточно денег"
  you-no-team: "Вы не состоите в команде"
  member-kick: "Участник %player% был исключён из команды."
  no-spawn-teleport: "Вы не можете телепортироваться на спавн во время решающего боя"
  you-pay: "Вы передали %money%$ тиммейту %target%. Ваш новый баланс: %balance%$"
  where-pay: "Тиммейт %player% передал Вам %money%$. Ваш новый баланс: %balance%$"
  no-local-chat: "§cВам недоступен командный чат. Можете использовать глобальный (!)"
  no-join-no-prepare: "В настоящий момент не ведётся набор участников."
  player-team-join: "Игрок %player% присоединился к команде."
  death-active: "Игрок %team-prefix% %player% погиб и потерял %balance%$."
  death-battle: "Игрок %team-prefix% %player% погиб и выбывает из игры."
  leave-team: "Игрок %player% покинул команду."
  no-keep-inventory: "Вам нечего возвращать."
  keep-inventory-notify:
    - ""
    - "§x§f§b§5§8§1§3Посетите хранителя, чтобы выкупить свой инвентарь!"
    - "§cЕсли Вы погибните еще раз, старый инвентарь выкупить будет нельзя!"
    - ""
  prepare-start:
    - ""
    - "§x§f§b§5§8§1§3Началась подготовка к игре!"
    - "§x§f§b§5§8§1§3Выберите команду §f(/tw join),§x§f§b§5§8§1§3 чтобы присоединиться."
    - ""
  battle-start-title: "§x§a§f§0§1§3§5В атаку!"

flags:
  - flag: ENTRY
    state: DENY
  - flag: PVP
    state: DENY
  - flag: FALL-DAMAGE
    state: ALLOW

teams:
  green:
    prefix: "§x§0§b§a§f§1§c■ §f"
    item-element:
      slot: 10
      material: GREEN_SHULKER_BOX
      display: "§x§0§b§a§f§1§cЗелёная команда"
    region:
      min:
        x: 0
        y: 0
        z: 0
      max:
        x: 200
        y: 256
        z: 200
    nether-region:
      min:
        x: 79
        y: -250
        z: 31
      max:
        x: 16
        y: 400
        z: -31
    spawn-point:
      x: 10
      y: 100
      z: 10
    nether-spawn-point:
      x: 10
      y: 100
      z: 10
    members:
      zako:
        balance: 0
  red:
    prefix: "§x§a§f§0§1§3§5■ §f"
    item-element:
      slot: 15
      material: RED_SHULKER_BOX
      display: "§x§a§f§0§1§3§5Красная команда"
    region:
      min:
        x: 0
        y: 0
        z: 0
      max:
        x: 200
        y: 256
        z: 200
    nether-region:
      min:
        x: 0
        y: 0
        z: 0
      max:
        x: 200
        y: 256
        z: 200
    spawn-point:
      x: 10
      y: 100
      z: 10
    nether-spawn-point:
      x: 10
      y: 100
      z: 10
    members:
      _Smoup:
        balance: 0