name: TeamWars
version: '${version}'
main: eventserver.teamwars.TeamWars
author: Zako
api-version: 1.19
depend:
  - WorldGuard
  - WorldEdit
  - PlaceholderAPI
commands:
  spawn:
  teamwars:
    aliases: ["tw"]
